- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    break_system_packages: true

- name: Install github3.py
  ansible.builtin.pip:
    name: github3.py
    break_system_packages: true

- name: Symlink python to python3
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
