- name: Make user directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    mode: "0750"
    recurse: true
  with_items:
    - /home/{{ vm_user }}/.config/regolith3/i3xrocks/conf.d/
    - /home/{{ vm_user }}/.config/regolith/i3/config/config.d/

# START Work-around until this is fixed: https://github.com/regolith-linux/regolith-desktop/issues/504
# Copy /usr/share/regolith/common/config.d/40_workspace-config to ~/.config/regolith/i3/config/config.d
# - name: Copy i3 configuration
#   ansible.builtin.copy:
#     src: files/40_workspace-config
#     dest: /home/{{ vm_user }}/.config/regolith/i3/config/config.d/40_workspace-config
#     mode: "0775"
#     owner: "{{ vm_user }}"
#     group: "{{ vm_user }}"
#     force: true
# END Work-around until this is fixed: https://github.com/regolith-linux/regolith-desktop/issues/504

- name: Default Window Manager to regolith
  ansible.builtin.copy:
    src: files/wm
    dest: /var/lib/AccountsService/users/{{ vm_user }}
    mode: "0644"
    owner: root
    group: root
    force: true

- name: Set login logo
  ansible.builtin.copy:
    src: files/face.png
    dest: /home/user/.face
    mode: "0640"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: Copy i3xrocks configuration
  ansible.builtin.copy:
    remote_src: true
    src: /usr/share/i3xrocks/conf.d/
    dest: /home/{{ vm_user }}/.config/regolith3/i3xrocks/conf.d/
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    mode: u=rwX,g=rX,o=rX

- name: Chown i3xrocks configuration
  ansible.builtin.command:
    cmd: "chown -R {{ vm_user }}:{{ vm_user }} /home/{{ vm_user }}/.config/regolith3/"

- name: Copy net-ip config
  ansible.builtin.copy:
    src: files/15_net-ip
    dest: /home/{{ vm_user }}/.config/regolith3/i3xrocks/conf.d/15_net-ip
    mode: "0775"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: Copy net-ip script
  ansible.builtin.copy:
    src: files/net-ip
    dest: /usr/share/i3xrocks/scripts/net-ip
    mode: "0775"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: Copy Xresources
  ansible.builtin.copy:
    src: files/Xresources
    dest: /home/{{ vm_user }}/.config/regolith3/Xresources
    mode: "640"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true
