- name: "Stop and disable {{ item.name }} service"
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
    enabled: false
  ignore_errors: true

- name: "Remove {{ item.name }} package"
  ansible.builtin.apt:
    name: "{{ item.name }}"
    force: true
    install_recommends: false
    purge: true
    state: absent

- name: "Prevent {{ item.name }} from being upgraded"
  ansible.builtin.dpkg_selections:
    name: "{{ item.name }}"
    selection: hold
  ignore_errors: true

- name: "Set pref file for exclusion of {{ item.name }}"
  ansible.builtin.template:
    src: templates/apt.pref
    dest: "/etc/apt/preferences.d/no-{{ item.name }}.pref"
    mode: "644"
