- name: Make /opt/notes
  ansible.builtin.file:
    path: /opt/notes
    state: directory
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    mode: "755"

- name: Install Active-Directory-Exploitation-Cheat-Sheet # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/S1ckB0y1337/Active-Directory-Exploitation-Cheat-Sheet.git
    dest: /opt/notes/windows/ad/cheatsheet/s1ckb0y1337
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install wadcoms # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/WADComs/WADComs.github.io.git
    dest: /opt/notes/windows/wadcoms
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install redcrypt # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/tymyrddin/red-crypt.git
    dest: /opt/notes/general/redcrypt
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install PayloadsAllTheThings # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/swisskyrepo/PayloadsAllTheThings.git
    dest: /opt/notes/general/payloadsallthethings
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install InternalAllTheThings # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/swisskyrepo/InternalAllTheThings.git
    dest: /opt/notes/windows/internalallthethings
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install P.P.N. # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/snovvcrash/PPN.git
    dest: /opt/notes/windows/ppn
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install Win32_Offensive_Cheatsheet # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/matthieu-hackwitharts/Win32_Offensive_Cheatsheet.git
    dest: /opt/notes/windows/cheatsheet/win32offensive
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install RedTeaming-Tactics-and-Techniques # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/mantvydasb/RedTeaming-Tactics-and-Techniques.git
    dest: /opt/notes/windows/cheatsheet/redteamingtacticsandtechniques
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install LOLDrivers # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/magicsword-io/LOLDrivers.git
    dest: /opt/notes/windows/loldrivers
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install HackTricks # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/HackTricks-wiki/hacktricks.git
    dest: /opt/notes/general/hacktricks
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install The-Hacker-Recipes # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/ShutdownRepo/The-Hacker-Recipes.git
    dest: /opt/notes/general/thehackerrecipes
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install ExploitDB # noqa latest[git]
  ansible.builtin.git:
    repo: https://gitlab.com/exploit-database/exploitdb.git
    dest: /opt/notes/exploitdb
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install PrivFu # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/daem0nc0re/PrivFu.git
    dest: /opt/notes/privfu
    depth: 1
  become: true
  become_user: "{{ vm_user }}"

- name: Install VX-API # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/vxunderground/VX-API.git
    dest: /opt/notes/vxapi
    depth: 1
  become: true
  become_user: "{{ vm_user }}"
