- name: Install Reverse SSH
  ansible.builtin.git:
    repo: https://github.com/NHAS/reverse_ssh.git
    dest: "{{ vm_tool_base }}/rssh"
    depth: 1

- name: Build Reverse SSH docker image
  community.docker.docker_image:
    build:
      path: "{{ vm_tool_base }}/rssh"
    name: rssh
    tag: local
    source: build

- name: Copy entrypoint script
  ansible.builtin.copy:
    src: files/rssh/rssh.sh
    dest: "{{ vm_tool_base }}/rssh/"
    mode: "0755"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: Symlink rssh entrypoint
  ansible.builtin.file:
    src: "{{ vm_tool_base }}/rssh/rssh.sh"
    dest: /usr/local/bin/rssh
    state: link
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
